import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
const bpm=Number(process.env.BPM||115), file=`dist/12-bar-blues-${bpm}bpm-alpha.mov`;
if(!existsSync(file)) throw new Error(`Missing ${file}; run npm run export first.`);
const outputs=[file,`dist/12-bar-blues-${bpm}bpm-alpha.webm`,`dist/12-bar-blues-${bpm}bpm-preview.mp4`,'dist/control-start.png','dist/control-bar-05-mid.png','dist/control-turnaround.png','dist/render-manifest.json'];
for(const output of outputs) if(!existsSync(output)) throw new Error(`Missing required output: ${output}`);
const probe=target=>{const p=spawnSync('ffprobe',['-v','error','-select_streams','v:0','-show_entries','stream=codec_name,width,height,pix_fmt,r_frame_rate,nb_frames:stream_tags=alpha_mode:format=duration','-of','json',target],{encoding:'utf8'});if(p.status)throw new Error(p.stderr);return JSON.parse(p.stdout)};
const data=probe(file), s=data.streams[0], frames=Math.round((2880/bpm)*60), manifest=JSON.parse(readFileSync('dist/render-manifest.json'));
const checks={codec:s.codec_name==='prores',size:s.width===1080&&s.height===1920,fps:s.r_frame_rate==='60/1',alpha:/yuva/.test(s.pix_fmt),frames:Number(s.nb_frames)===frames,duration:Math.abs(Number(data.format.duration)-frames/60)<.001};
const webm=probe(outputs[1]).streams[0], mp4=probe(outputs[2]).streams[0];
Object.assign(checks,{webmCodec:webm.codec_name==='vp9',webmAlpha:webm.tags?.ALPHA_MODE==='1'||webm.tags?.alpha_mode==='1',previewCodec:mp4.codec_name==='h264',manifest:manifest.bpm===115&&manifest.fps===60&&manifest.width===1080&&manifest.height===1920&&manifest.timeSignature==='4/4'&&manifest.bars===12&&manifest.beats===48&&manifest.form.join(' ')==='I I I I IV IV I I V IV I V'});
for(const [k,v] of Object.entries(checks)) console.log(`${v?'PASS':'FAIL'} ${k}`); if(Object.values(checks).includes(false)) process.exit(1);
for(let bar=0;bar<12;bar++) console.log(`bar ${String(bar+1).padStart(2,'0')}: frame ${Math.round(bar*240/bpm*60)} / t=${(bar*240/bpm).toFixed(10)}s`);
for(let beat=0;beat<48;beat++) if(Math.abs(beat*60/bpm-(beat*60/bpm))>1e-12) throw Error('beat arithmetic');
console.log('PASS 48 absolute-time beat starts');
const report={verifiedAt:new Date().toISOString(),outputs,checks,barStarts:Array.from({length:12},(_,bar)=>({bar:bar+1,time:bar*240/bpm,frame:Math.round(bar*240/bpm*60)})),beatStarts:Array.from({length:48},(_,beat)=>({beat:beat+1,time:beat*60/bpm,downbeat:beat%4===0}))};
writeFileSync('dist/verification-report.json',JSON.stringify(report,null,2));
